# Generated by Django 5.2.6 on 2025-10-03 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferenceApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='description',
            field=models.TextField(default=0, validators=[django.core.validators.MinLengthValidator(30, 'description must be at least 30 characters long')]),
            preserve_default=False,
        ),
    ]
